drop table if exists t_user;
create table t_user
(
    id                bigint             not null auto_increment primary key,
    username          varchar(64)        not null,
    email             varchar(256)       not null,
    password          varchar(256)       not null,
    flag              smallint default 1 not null,
    created_by        varchar(64),
    created_date      datetime           not null,
    last_updated_by   varchar(64),
    last_updated_date datetime           not null
) ENGINE = InnoDB
  AUTO_INCREMENT = 100000
  DEFAULT CHARSET = utf8mb4;

drop table if exists t_role;
create table t_role
(
    id                bigint             not null auto_increment primary key,
    role_code         varchar(64)        not null,
    flag              smallint default 1 not null,
    created_by        varchar(64),
    created_date      datetime           not null,
    last_updated_by   varchar(64),
    last_updated_date datetime           not null
) ENGINE = InnoDB
  AUTO_INCREMENT = 100000
  DEFAULT CHARSET = utf8mb4;

drop table if exists t_user_role;
create table t_user_role
(
    id                bigint             not null auto_increment primary key,
    user_id           bigint             not null,
    role_id           bigint             not null,
    flag              smallint default 1 not null,
    created_by        varchar(64),
    created_date      datetime           not null,
    last_updated_by   varchar(64),
    last_updated_date datetime           not null,
    UNIQUE KEY user_id_role_id (user_id, role_id)
) ENGINE = InnoDB
  AUTO_INCREMENT = 100000
  DEFAULT CHARSET = utf8mb4;

drop table if exists t_permission;
create table t_permission
(
    id                bigint             not null auto_increment primary key,
    permission_code   varchar(64)        not null,
    flag              smallint default 1 not null,
    created_by        varchar(64),
    created_date      datetime           not null,
    last_updated_by   varchar(64),
    last_updated_date datetime           not null
) ENGINE = InnoDB
  AUTO_INCREMENT = 100000
  DEFAULT CHARSET = utf8mb4;

drop table if exists t_role_permission;
create table t_role_permission
(
    id                bigint             not null auto_increment primary key,
    role_id           bigint             not null,
    permission_id     bigint             not null,
    flag              smallint default 1 not null,
    created_by        varchar(64),
    created_date      datetime           not null,
    last_updated_by   varchar(64),
    last_updated_date datetime           not null,
    UNIQUE KEY permission_id_role_id (role_id, permission_id)
) ENGINE = InnoDB
  AUTO_INCREMENT = 100000
  DEFAULT CHARSET = utf8mb4;

INSERT INTO test.t_user (username, email, password, flag, created_by, created_date, last_updated_by, last_updated_date)
VALUES ('admin1', 'admin1@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin2', 'admin2@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin3', 'admin3@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin4', 'admin4@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin5', 'admin5@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin6', 'admin6@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin7', 'admin7@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin8', 'admin8@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin9', 'admin9@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin10', 'admin10@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin11', 'admin11@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin12', 'admin12@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin13', 'admin13@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin14', 'admin14@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin15', 'admin15@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin16', 'admin16@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin17', 'admin17@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin18', 'admin18@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin19', 'admin19@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin20', 'admin20@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin21', 'admin21@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin22', 'admin22@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin23', 'admin23@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin24', 'admin24@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin25', 'admin25@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin26', 'admin26@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin27', 'admin27@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin28', 'admin28@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin29', 'admin29@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin30', 'admin30@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin31', 'admin31@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin32', 'admin32@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin33', 'admin33@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin34', 'admin34@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin35', 'admin35@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin36', 'admin36@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin37', 'admin37@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin38', 'admin38@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin39', 'admin39@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin40', 'admin40@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin41', 'admin41@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin42', 'admin42@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin43', 'admin43@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin44', 'admin44@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin45', 'admin45@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin46', 'admin46@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin47', 'admin47@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin48', 'admin48@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin49', 'admin49@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin50', 'admin50@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin51', 'admin51@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin52', 'admin52@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin53', 'admin53@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin54', 'admin54@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin55', 'admin55@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin56', 'admin56@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin57', 'admin57@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin58', 'admin58@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin59', 'admin59@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin60', 'admin60@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin61', 'admin61@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin62', 'admin62@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin63', 'admin63@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin64', 'admin64@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin65', 'admin65@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin66', 'admin66@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin67', 'admin67@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin68', 'admin68@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin69', 'admin69@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin70', 'admin70@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin71', 'admin71@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin72', 'admin72@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin73', 'admin73@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin74', 'admin74@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin75', 'admin75@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin76', 'admin76@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin77', 'admin77@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin78', 'admin78@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin79', 'admin79@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin80', 'admin80@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin81', 'admin81@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin82', 'admin82@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin83', 'admin83@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin84', 'admin84@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin85', 'admin85@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin86', 'admin86@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin87', 'admin87@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin88', 'admin88@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin89', 'admin89@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin90', 'admin90@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin91', 'admin91@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin92', 'admin92@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin93', 'admin93@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin94', 'admin94@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin95', 'admin95@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin96', 'admin96@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin97', 'admin97@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin98', 'admin98@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin99', 'admin99@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin100', 'admin100@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin101', 'admin101@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin102', 'admin102@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin103', 'admin103@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin104', 'admin104@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin105', 'admin105@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin106', 'admin106@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin107', 'admin107@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin108', 'admin108@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin109', 'admin109@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin110', 'admin110@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin111', 'admin111@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin112', 'admin112@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin113', 'admin113@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin114', 'admin114@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin115', 'admin115@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin116', 'admin116@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin117', 'admin117@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin118', 'admin118@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin119', 'admin119@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin120', 'admin120@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin121', 'admin121@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin122', 'admin122@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin123', 'admin123@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin124', 'admin124@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin125', 'admin125@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin126', 'admin126@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin127', 'admin127@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin128', 'admin128@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin129', 'admin129@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin130', 'admin130@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin131', 'admin131@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin132', 'admin132@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin133', 'admin133@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin134', 'admin134@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin135', 'admin135@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin136', 'admin136@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin137', 'admin137@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin138', 'admin138@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin139', 'admin139@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin140', 'admin140@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin141', 'admin141@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin142', 'admin142@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin143', 'admin143@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin144', 'admin144@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin145', 'admin145@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin146', 'admin146@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin147', 'admin147@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin148', 'admin148@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin149', 'admin149@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin150', 'admin150@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin151', 'admin151@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin152', 'admin152@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin153', 'admin153@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin154', 'admin154@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin155', 'admin155@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin156', 'admin156@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin157', 'admin157@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin158', 'admin158@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin159', 'admin159@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin160', 'admin160@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin161', 'admin161@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin162', 'admin162@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin163', 'admin163@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin164', 'admin164@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin165', 'admin165@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin166', 'admin166@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin167', 'admin167@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin168', 'admin168@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin169', 'admin169@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin170', 'admin170@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin171', 'admin171@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin172', 'admin172@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin173', 'admin173@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin174', 'admin174@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin175', 'admin175@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin176', 'admin176@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin177', 'admin177@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin178', 'admin178@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin179', 'admin179@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin180', 'admin180@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin181', 'admin181@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin182', 'admin182@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin183', 'admin183@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin184', 'admin184@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin185', 'admin185@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin186', 'admin186@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin187', 'admin187@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin188', 'admin188@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin189', 'admin189@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin190', 'admin190@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin191', 'admin191@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin192', 'admin192@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin193', 'admin193@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin194', 'admin194@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin195', 'admin195@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin196', 'admin196@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin197', 'admin197@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin198', 'admin198@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin199', 'admin199@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate()),
       ('admin200', 'admin200@mail.com', '123qwe', DEFAULT, null, sysdate(), null, sysdate());

INSERT INTO test.t_role (role_code, flag, created_by, created_date, last_updated_by, last_updated_date)
VALUES ('SYSTEM_ADMINISTRATOR', DEFAULT, null, sysdate(), null, sysdate()),
       ('SYSTEM_ROLE_ADMINISTRATOR', DEFAULT, null, sysdate(), null, sysdate()),
       ('SYSTEM_ROLE_GRANT_ADMINISTRATOR', DEFAULT, null, sysdate(), null, sysdate()),
       ('ROLE_ADMINISTRATOR', DEFAULT, null, sysdate(), null, sysdate()),
       ('ROLE_GRANT_ADMINISTRATOR', DEFAULT, null, sysdate(), null, sysdate()),
       ('USER_ADMINISTRATOR', DEFAULT, null, sysdate(), null, sysdate()),
       ('AUDITOR', DEFAULT, null, sysdate(), null, sysdate());

INSERT INTO test.t_permission (permission_code, flag, created_date, last_updated_date)
VALUES ('SYSTEM_ADMINISTRATOR_CREATE', DEFAULT, sysdate(), sysdate()),
       ('SYSTEM_ADMINISTRATOR_READ', DEFAULT, sysdate(), sysdate()),
       ('SYSTEM_ADMINISTRATOR_EDIT', DEFAULT, sysdate(), sysdate()),
       ('SYSTEM_ADMINISTRATOR_DELETE', DEFAULT, sysdate(), sysdate()),
       ('SYSTEM_ROLE_ADMINISTRATOR_CREATE', DEFAULT, sysdate(), sysdate()),
       ('SYSTEM_ROLE_ADMINISTRATOR_READ', DEFAULT, sysdate(), sysdate()),
       ('SYSTEM_ROLE_ADMINISTRATOR_EDIT', DEFAULT, sysdate(), sysdate()),
       ('SYSTEM_ROLE_ADMINISTRATOR_DELETE', DEFAULT, sysdate(), sysdate()),
       ('SYSTEM_ROLE_GRANT_ADMINISTRATOR_CREATE', DEFAULT, sysdate(), sysdate()),
       ('SYSTEM_ROLE_GRANT_ADMINISTRATOR_READ', DEFAULT, sysdate(), sysdate()),
       ('SYSTEM_ROLE_GRANT_ADMINISTRATOR_EDIT', DEFAULT, sysdate(), sysdate()),
       ('SYSTEM_ROLE_GRANT_ADMINISTRATOR_DELETE', DEFAULT, sysdate(), sysdate()),
       ('ROLE_ADMINISTRATOR_CREATE', DEFAULT, sysdate(), sysdate()),
       ('ROLE_ADMINISTRATOR_READ', DEFAULT, sysdate(), sysdate()),
       ('ROLE_ADMINISTRATOR_EDIT', DEFAULT, sysdate(), sysdate()),
       ('ROLE_ADMINISTRATOR_DELETE', DEFAULT, sysdate(), sysdate()),
       ('ROLE_GRANT_ADMINISTRATOR_CREATE', DEFAULT, sysdate(), sysdate()),
       ('ROLE_GRANT_ADMINISTRATOR_READ', DEFAULT, sysdate(), sysdate()),
       ('ROLE_GRANT_ADMINISTRATOR_EDIT', DEFAULT, sysdate(), sysdate()),
       ('ROLE_GRANT_ADMINISTRATOR_DELETE', DEFAULT, sysdate(), sysdate()),
       ('USER_ADMINISTRATOR_CREATE', DEFAULT, sysdate(), sysdate()),
       ('USER_ADMINISTRATOR_READ', DEFAULT, sysdate(), sysdate()),
       ('USER_ADMINISTRATOR_EDIT', DEFAULT, sysdate(), sysdate()),
       ('USER_ADMINISTRATOR_DELETE', DEFAULT, sysdate(), sysdate()),
       ('AUDITOR_CREATE', DEFAULT, sysdate(), sysdate()),
       ('AUDITOR_READ', DEFAULT, sysdate(), sysdate()),
       ('AUDITOR_EDIT', DEFAULT, sysdate(), sysdate()),
       ('AUDITOR_DELETE', DEFAULT, sysdate(), sysdate());

insert into t_user_role (user_id, role_id, flag, created_date, last_updated_date)
values ((select id from t_user where username = 'admin1'),
        (select id from t_role where role_code = 'SYSTEM_ADMINISTRATOR'), DEFAULT, sysdate(), sysdate()),
       ((select id from t_user where username = 'admin1'),
        (select id from t_role where role_code = 'SYSTEM_ROLE_ADMINISTRATOR'), DEFAULT, sysdate(), sysdate()),
       ((select id from t_user where username = 'admin1'),
        (select id from t_role where role_code = 'SYSTEM_ROLE_GRANT_ADMINISTRATOR'), DEFAULT, sysdate(), sysdate()),
       ((select id from t_user where username = 'admin1'),
        (select id from t_role where role_code = 'ROLE_ADMINISTRATOR'), DEFAULT, sysdate(), sysdate()),
       ((select id from t_user where username = 'admin1'),
        (select id from t_role where role_code = 'USER_ADMINISTRATOR'), DEFAULT, sysdate(), sysdate());

insert into t_role_permission(role_id, permission_id, flag, created_date, last_updated_date)
values ((select id from t_role where role_code = 'SYSTEM_ADMINISTRATOR'),
        (select id from t_permission where permission_code = 'SYSTEM_ADMINISTRATOR_CREATE'),
        DEFAULT,
        sysdate(),
        sysdate()),
       ((select id from t_role where role_code = 'SYSTEM_ADMINISTRATOR'),
        (select id from t_permission where permission_code = 'SYSTEM_ADMINISTRATOR_READ'),
        DEFAULT,
        sysdate(),
        sysdate()),
       ((select id from t_role where role_code = 'SYSTEM_ADMINISTRATOR'),
        (select id from t_permission where permission_code = 'SYSTEM_ADMINISTRATOR_EDIT'),
        DEFAULT,
        sysdate(),
        sysdate()),
       ((select id from t_role where role_code = 'SYSTEM_ADMINISTRATOR'),
        (select id from t_permission where permission_code = 'SYSTEM_ADMINISTRATOR_DELETE'),
        DEFAULT,
        sysdate(),
        sysdate());
